#!/bin/bash

URL="http://127.0.0.1/frostybot"
COMMAND="$@"
CURRENTPATH=`pwd`
SCRIPTPATH=`dirname "$(readlink -f "$0")"`

#echo "$SCRIPTPATH"

for x in "start" "stop" "status" "debug"; do
    if [ "$COMMAND" == "$x" ]; then
        cd "$SCRIPTPATH"
        pwd
        ./scripts/$x
        cd "$CURRENTPATH"
        exit
    fi
done

WGETCMD="wget --no-check-certificate --method POST --header 'accept: application/json' --header 'cache-control: no-cache' --header 'Content-Type: text/plain' --body-data '$COMMAND' -qO- $URL"
eval "$WGETCMD | jq"
