#!/bin/bash

COMMAND="$@"
CURRENTPATH=`pwd`
SCRIPTPATH=`dirname "$(readlink -f "$0")"`
PORTCFG="$SCRIPTPATH/.port"

if [ -f "$PORTCFG" ]; then
    PORT=`cat $PORTCFG`
else
    PORT=80
fi

URL="http://127.0.0.1:$PORT/frostybot"

for x in "autostart" "start" "stop" "status" "debug" "upgrade" "test"; do
    if [ "$COMMAND" == "$x" ]; then
        cd "$SCRIPTPATH"
        ./scripts/$x
        cd "$CURRENTPATH"
        exit
    fi
done

WGETCMD="wget --no-check-certificate --method POST --header 'accept: application/json' --header 'cache-control: no-cache' --header 'Content-Type: text/plain' --body-data '$COMMAND' -qO- $URL"
eval "$WGETCMD | jq"
