#!/bin/bash

sudo crontab -l | grep -iv frostybot | grep -iv "no crontab" > /tmp/tmpcron
sudo echo "" >> /tmp/tmpcron
sudo echo "# Automatically start Frostybot when server reboots" >> /tmp/tmpcron
sudo echo "@reboot frostybot start > /dev/null 2>&1" >> /tmp/tmpcron
sudo crontab /tmp/tmpcron
sudo rm /tmp/tmpcron 

echo "Frostybot will now start automatically when the server is rebooted"