#!/bin/bash

sudo crontab -l | grep -iv frostybot | grep -vc "no crontab" > /tmp/tmpcron
sudo echo "@reboot frostybot start > /dev/null 2>&1" >> /tmp/tmpcron
sudo cat /tmp/tmpcron
sudo crontab /tmp/tmpcron
sudo rm /tmp/tmpcron 

echo "Frostybot will now start automatically when the server is rebooted"