#!/bin/bash

PID=`sudo ps ax | grep "frostybot-js" | grep -v grep | awk '{print $1}'`
CURRENTPATH=`pwd`
SCRIPTPATH=`dirname "$(readlink -f "$0")"`

cd "$SCRIPTPATH" &
cd ../ &

echo "Checking for updates..."
sudo git checkout stable > /dev/null 2>&1
sudo git fetch > /dev/null 2>&1
CHECK=`sudo git status | grep "up to date" | wc -l`

if [ "$CHECK" -eq "1" ]; then
  echo "Frostybot is up to date, no upgrade is required"
else
  echo "Frostybot updates available, proceeding with upgrade"
  if [ ! "$PID" == "" ]; then
    ./scripts/stop
    while [ ! "$PID" == "" ]; do
      sleep 2
      PID=`sudo ps ax | grep "frostybot-js" | grep -v grep | awk '{print $1}'`
    done
    cd "$CURRENTPATH" &
    DOSTART="true"
  else
    DOSTART="false"
  fi
  echo "Frostybot server stopped successfully, upgrading now"
  echo "Updating Frostybot files from Github"
  sudo git checkout stable > /dev/null 2>&1
  sudo git pull -f
  echo "Updating MOTD"
  cp -f /usr/local/frostybot-js/scripts/motd /etc/motd
  echo "Installing outstanding NodeJS modules"
  sudo npm install --unsafe-perm > /dev/null 2>&1
  echo "Updating existing NodeJS modules"
  sudo npm upgrade > /dev/null 2>&1
  if [ "$DOSTART" == "true" ]; then
    ./scripts/start
    while [ "$PID" == "" ]; do
      sleep 2
      PID=`sudo ps ax | grep "frostybot-js" | grep -v grep | awk '{print $1}'`
    done
    echo "Frostybot server started"
  fi
  echo "Upgrade complete"
fi
cd "$CURRENTPATH" &
